### ISSUE TITLE
Issues deploying

### ISSUE THREAD

**Issue by Tam2** [caprover/deploy-from-github#5]
I'm having some issues with deploying, it keeps giving me the below error:

(I do have a special path for captain-definition, it's just the hash error)

```
Preparing deployment to CapRover...

**** Warning ****
No captain-definition was found in main directory: unless you have specified a special path for your captain-definition, this build will fail!

Ensuring authentication...
Cannot find hash of last commit on branch "master".
```

This is how i've got my workflow set-up

```yaml
name: API Tests
env:
  PORT: 4000
on:
  push:
    branches: [ "master" ]

jobs:
  build_and_test:
      runs-on: ubuntu-latest
      
      strategy:
        matrix:
          node-version: [18.x]

      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: "npm"
            
          
        - name: Deploy Github repo to Caprover
          uses: caprover/deploy-from-github@main
          with:
            server: http://captain.domain.xxx
            token: <redacted>
            app: api-qa
            branch: master

        - name: Run API Tests
          uses: anthonyvscode/newman-action@v1
          with:
            collection: /tests/collection.json
            reporters: cli

        - name: Output summary to console
          run: echo ${{ steps.run-newman.outputs.summary }}
```
