### ISSUE TITLE
You don't think this is better?

### ISSUE THREAD

**Issue by mohitxskull** [caprover/deploy-from-github#8]
```yml
name: Stats Backend Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - run: yarn global add turbo

      - run: yarn prune:back-stats

      - run: |
          cp ./captain-definition ./out
          cp ./Dockerfile ./out

      - run: |
          cd out
          tar -czvf ./deploy.tar ./*
          mv ./deploy.tar ../

      - uses: caprover/deploy-from-github@main
        with:
          server: '${{ secrets.CAP_SERVER }}'
          app: '${{ secrets.BACK_STATS_APP }}'
          token: '${{ secrets.BACK_STATS_TOKEN }}'

```
